### ISSUE TITLE
Can't put 4 boxes in a row

### ISSUE THREAD

**Issue by RyanNicholasPurdy** [RyanNicholasPurdy/MyGeofilter.ca#1]
@thomasjbradley

Hey Thomas,

I was trying to create 4 boxes in a row using gridifier & wasn't able to do so. My theory was I could create a 1/2 div, and put two more 1/2 div's inside it. Unfortunately (as seen) the boxes wont align.

Sos - thank you in advance,
-R

**Comment by thomasjbradley** [comment]
When you generated the grid did you choose up to 4 columns?

**Comment by RyanNicholasPurdy** [comment]
@thomasjbradley I had no idea we could up the amount of columns! I've since fixed it and it's working perfectly, thank you so much! (:
